// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/GetToken": {
            "post": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "access"
                ],
                "summary": "GetToken Method",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "User email",
                        "name": "userEmail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "userPassword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/Login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access"
                ],
                "summary": "Login Method",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "User email",
                        "name": "userEmail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "userPassword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/Logoff": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access"
                ],
                "summary": "Logoff Method",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/Register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "access"
                ],
                "summary": "Register Method",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "User email",
                        "name": "userEmail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "userPassword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "main.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
